version: "3"
services:
  intellijlogger:
    image: cs125/intellijlogger:latest
    depends_on:
      - mongodb
    ports:
      - 8818:8888
    environment:
      - MONGODB=mongodb://mongodb/cs125
      - SEMESTER=Fall2023
  mongodb:
    image: mongo:6.0.8
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
